# Generated by Django 2.0 on 2020-10-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblisting_listing_kws'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='application_deadline',
        ),
    ]
