# Generated by Django 2.0 on 2020-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_joblisting_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('Web Design', 'Web Design'), ('Graphic Design', 'Graphic Design'), ('Web Developing', 'Web Developing'), ('Software Engineering', 'Software Engineering'), ('HR', 'HR'), ('Administrative & Customer Support', 'Administrative & Customer Support,'), ('Architecture & Engineering', '       Architecture & Engineering,'), ('Community & Human Services', '       Community & Human Services,'), ('Construction & Extraction', '        Construction & Extraction,'), ('Education & Instruction', '          Education & Instruction,'), ('Finance & Accounting', '             Finance & Accounting,'), ('Flight Attendant', '                 Flight Attendant,'), ('Food & Beverage', '                  Food & Beverage,'), ('Healthcare', '                       Healthcare,'), ('Legal', '                            Legal,'), ('Marketing, Advertising & Public Relations', 'Marketing, Advertising & Public Relations'), ('Personal Services', '                Personal Services,'), ('Protective & Security', '            Protective & Security,'), ('Repair, Maintenance & Installation', 'Repair, Maintenance & Installation,'), ('Sales & Retail', '                   Sales & Retail,'), ('Technology', '                       Technology,'), ('Transportation', '                   Transportation,'), ('Travel, Attractions & Events', '     Travel, Attractions & Events,')], max_length=30),
        ),
    ]
